name: build jobs

on:
  push:
    tags:
      - '*'

jobs:
  build-image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ""
          draft: false
          prerelease: false

#      - name: Zip file
#        run: |
#          tag_t="${{ github.ref }}"
#          tag="${tag_t##*/}"
#          cd extend/payment/
#          zip justap-shopxo-plugin-v${tag}.zip *
#          mv justap-shopxo-plugin-v${tag}.zip ../../
#
#      - name: Upload file to oss
#        id: upload_to_oss
#        uses: tvrcgo/upload-to-oss@master
#        with:
#          key-id: ${{ secrets.OSS_KEY_ID }}
#          key-secret: ${{ secrets.OSS_KEY_SECRET }}
#          region: ${{ secrets.OSS_KEY_REGION }}
#          bucket: ${{ secrets.OSS_KEY_BUCKET_NAME }}
#          assets: |
#            *.zip:/
#
